#!/bin/bash

cd ~
sudo apt-add-repository --yes ppa:neovim-ppa/unstable
sudo apt update
sudo apt install --yes zsh neovim python-dev python-pip python3-dev python3-pip zsh-antigen thefuck nodejs npm silversearcher-ag
pip3 install neovim-remote
sudo update-alternatives --install /usr/bin/vi vi /usr/bin/nvim 60
sudo update-alternatives --install /usr/bin/vim vim /usr/bin/nvim 60
sudo update-alternatives --config vim
sudo update-alternatives --install /usr/bin/editor editor /usr/bin/nvim 60
curl -L git.io/antigen > antigen.zsh
chsh -s /bin/zsh
curl -fLo ~/.config/nvim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
mkdir -p ~/.vim/backup
mkdir -p ~/.vim/undo
nvim "+PlugInstall --sync"
nvim "+UpdateRemotePlugins"
